#!/bin/sh

noteFilename="$HOME/vimwiki/diary/note-$(date +%Y-%m-%d).md"

if [ ! -f $noteFilename ]; then
  echo "# Notes for $(date +%Y-%m-%d)" > $noteFilename
fi

vim -c "norm Go" \
  -c "norm Go## $(date +%H:%M)" \
  -c "norm o### TOPIC: " \
  -c "norm zz" \
  -c "startinsert" $noteFilename
